"""rename department

Revision ID: 65aaecc9ce9b
Revises: df71e29f10b4
Create Date: 2025-03-26 23:32:27.519267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aaecc9ce9b'
down_revision = 'df71e29f10b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('departments',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('name', sa.String(), nullable=False),
    #sa.Column('address', sa.String(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('department',
    #sa.Column('id', sa.INTEGER(), nullable=False),
    #sa.Column('name', sa.VARCHAR(), nullable=False),
    #sa.Column('address', sa.VARCHAR(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
