"""rename address

Revision ID: 8a4aba722e31
Revises: 65aaecc9ce9b
Create Date: 2025-03-26 23:38:16.614372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4aba722e31'
down_revision = '65aaecc9ce9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    #op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    #op.drop_column('departments', 'location')
    # ### end Alembic commands ###
